### ISSUE TITLE
Implement an AugmentedJWT serializer/deserializer

### ISSUE THREAD

**Issue by jarreds** [jmcardon/tsec#103]
To implement a token `BackingStore` for JWT we need the following:

```scala
new BackingStore[F, SecureRandomId, AugmentedJWT[HMACSHA256, UUID]] {
  def put(token: AugmentedJWT[HMACSHA256, UUID]): F[AugmentedJWT[HMACSHA256, UUID]] = ???
  def get(id: SecureRandomId): OptionT[F, AugmentedJWT[HMACSHA256, UUID]] = ???
  def update(token: AugmentedJWT[HMACSHA256, UUID]): F[AugmentedJWT[HMACSHA256, UUID]] = ???
  def delete(id: SecureRandomId): Eff[R, Unit] = ???
}
```

We need to serialize/deserialize the `AugmentedJWT` into a format that datastores can support.

My first thought is Circe encoders/decoders so we can go back and forth from a JSON string, but I'm open as long as there is some way to do it.

**Comment by jmcardon** [comment]
Hmm, 

If you mean a circe instance, this is all possible, as every thing has its own way to be encoded.

However, it's hard to say exactly how people will serialize this. you could save an `AugmentedJWT` in a DB, a hash table on Redis by key, etc.

It's an interesting thing to think about. I'm unsure whether we need so much a default serializer, but rather some guidelines on how to serialize

**Comment by jmcardon** [comment]
@jarreds I will be closing this ticket. Here's my rationale:

A `BackingStore` for an `AugmentedJWT` or any `Augmented` field can be implemented in many ways, such as:
- DB table with typed fields
- Redis hash table with typed fields (at the driver level anyway, stringy in redis :sob: )
- Some other in mem cache at the object level
- Mongo in a Json..

Should I go on? It's hard to say _how_ exactly to format it since it sort of depends on the user.

As far as a `Json` is concerned, there's no standard way to do it (that I'm aware of). The first two fields are json objects (base 64 URL-safe encoded), and the third is a base 64 URL-safe encoded signature. From there, you could choose say, typed keys with the sig as a hex string, or sig as an array of bytes... It really depends. If there is a standard json approach, I'd be happy to kick up the RFC tackle :D

Let me know if there's anything I can help you with, either here, or on gitter. Specifically though, I'm just unsure what a sane default is (if there is one).
